### ISSUE TITLE
Cannot install on my Samsung Galaxy S5

### ISSUE THREAD

**Issue by JohnGLFour** [Magisk-Modules-Repo/Heart-Rate-Sensor_Enabler#1]
Hello, this maybe the first issue of this repo, but I need to report it.

The issue is when I tried to install in Magisk it said installation failed, I tried to install in recovery it got an Error 2.

I screenshot this to proof I have Samsung Galaxy S5:
(And also this is Qualcomm Snapgradon 801, I checked it)
![Screenshot_Settings_20190630-154945](https://user-images.githubusercontent.com/17681926/60393906-edea1f80-9b0b-11e9-9621-5886ba7cf97a.png)

**Comment by sunilpaulmathew** [comment]
Thanks for reporting.
I'll look on it later (now too busy). I hope you are on the latest TWRP and Magisk version.
Bye the way, for my personal testing, I do not use neighter TWRP nor Magisk Manager, but my own [Flasher app](https://play.google.com/store/apps/details?id=com.smartpack.smartflasher).

**Comment by JohnGLFour** [comment]
Yes, it's klte. And yes, latest tarp and magisk
